sudo: required

env:
  - DOCKERFILE=py2/Dockerfile.cv300 TAG=py2-cv3.0.0
  - DOCKERFILE=py2/Dockerfile.cv310 TAG=py2-cv3.1.0
  - DOCKERFILE=py2/Dockerfile.cv320 TAG=py2-cv3.2.0
  - DOCKERFILE=py2/Dockerfile.cv330 TAG=py2-cv3.3.0
  - DOCKERFILE=py2/Dockerfile.cv340 TAG=py2-cv3.4.0
  - DOCKERFILE=py3/Dockerfile.cv300 TAG=py3-cv3.0.0
  - DOCKERFILE=py3/Dockerfile.cv310 TAG=py3-cv3.1.0
  - DOCKERFILE=py3/Dockerfile.cv320 TAG=py3-cv3.2.0
  - DOCKERFILE=py3/Dockerfile.cv330 TAG=py3-cv3.3.0
  - DOCKERFILE=py3/Dockerfile.cv340 TAG=py3-cv3.4.0

  - DOCKERFILE=py2/Dockerfile.cv300cuda8.0 TAG=py2-cv3.0.0-cuda8.0
  - DOCKERFILE=py2/Dockerfile.cv300cuda8.0cudnn5 TAG=py2-cv3.0.0-cuda8.0-cudnn5
  - DOCKERFILE=py2/Dockerfile.cv300cuda8.0cudnn6 TAG=py2-cv3.0.0-cuda8.0-cudnn6
  - DOCKERFILE=py2/Dockerfile.cv300cuda8.0cudnn7 TAG=py2-cv3.0.0-cuda8.0-cudnn7
  - DOCKERFILE=py2/Dockerfile.cv300cuda9.0 TAG=py2-cv3.0.0-cuda9.0
  - DOCKERFILE=py2/Dockerfile.cv300cuda9.0cudnn7 TAG=py2-cv3.0.0-cuda9.0-cudnn7
  - DOCKERFILE=py2/Dockerfile.cv300cuda9.1 TAG=py2-cv3.0.0-cuda9.1
  - DOCKERFILE=py2/Dockerfile.cv300cuda9.1cudnn7 TAG=py2-cv3.0.0-cuda9.1-cudnn7
  - DOCKERFILE=py2/Dockerfile.cv300cuda9.2 TAG=py2-cv3.0.0-cuda9.2
  - DOCKERFILE=py2/Dockerfile.cv300cuda9.2cudnn7 TAG=py2-cv3.0.0-cuda9.2-cudnn7

services:
  - docker

script:
  - docker build -f ${DOCKERFILE} -t djx339/py-opencv-ffmpeg:${TAG} .
